name: control_ventas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1 
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2
  firebase_core: ^2.30.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0
  shared_preferences: ^2.2.2
  oktoast: ^3.3.1

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
